### PR TITLE
chore: add link to docs in each eslint rule

### PR DESCRIPTION
**Pull request by k-yle**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request?

Improve the DX, particularly because many people expect eslint to only lint JS files. So making the docs easily accessible is important.

#### What changes did you make? (Give an overview)

Add [`docs.url`](https://eslint.org/docs/latest/extend/custom-rules#url) to every rule, so that you can click on the rule in your IDE to go directly to the documentation

#### Related Issues

&shy;-

#### Is there anything you'd like reviewers to focus on?

&shy;-

### CODE REVIEW

**Review by nzakas — APPROVED** [review]
LGTM. Thanks.

**Review by nzakas — CHANGES_REQUESTED** [review]
CI is failing because strings should use double quotes. Can you please update that?

**Comment by k-yle** [comment]
done

**Review by nzakas — APPROVED** [review]
Thanks.

**Pull request merged**
